version: 2.1
orbs:
  boost-security-scanner: boostsecurityio/scanner@4
workflows:
  build:
    jobs:
      - boost-security-scanner/scan:
          name: SBOM
          context: boost-security
          registry_module: boostsecurityio/trivy-sbom
      - boost-security-scanner/scan:
          name: Docker image scan
          context: boost-security
          registry_module: boostsecurityio/trivy-image
        environment:
          BOOST_IMAGE_NAME: ubuntu:jammy-20220101
