name: boost (Prod)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost_security_sast:
    name: SAST / Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1
      - name: Native Scanner module
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_enabled: false
#           api_token: ${{ secrets.BOOST_API_KEY_PROD }}
          registry_module: boostsecurityio/native-scanner
          pre_scan_cmd: |
            helm template canaries/helm/charts/hello-world --output-dir ./generated
