name: SAST - semgrep (dev)
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  scanner:
    name: boost
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup semgrep and converter
        run: |
          export SEMGREP_VERSION=0.112@sha256:22cdfb541673843cf8950df1a9cc386237435517f41f0d40bd9b7e306076441f
          export CONVERTER_VERSION=2aa6818@sha256:d9cbc9510eca206572e7fd17a0112284055c588bf188da685c715ad571b45896
          
          docker pull returntocorp/semgrep:$SEMGREP_VERSION
          docker pull public.ecr.aws/boostsecurityio/boost-scanner-semgrep:$CONVERTER_VERSION

          cat <<EOF > /tmp/semgrep-wrapper
          #!/bin/bash
          set -euo pipefail
          shopt -s inherit_errexit
          
          docker run \
            --rm -v "${PWD}:/src" \
            returntocorp/semgrep:$SEMGREP_VERSION \
            semgrep scan --json --quiet --config auto \
          |
          docker run \
            --rm \
            --interactive \
            public.ecr.aws/boostsecurityio/boost-scanner-semgrep:$CONVERTER_VERSION \
            process
          
          EOF
          chmod +x /tmp/semgrep-wrapper
          /tmp/semgrep-wrapper
#      - name: semgrep
#        uses: boostsecurityio/boostsec-scanner-github@v3
#        with:
#          action: exec
#          api_endpoint: https://api.dev.boostsec.io
#          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
#          exec_command: /tmp/semgrep-wrapper
#          step_name: semgrep
