name: dev.boostsec.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost_security_sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@bv4
        env:
          BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/scanner-registry.git#native-scanner/maybe-wrong-id
        with:
          api_endpoint: https://api.dev.boostsec.io
          api_token: ${{ secrets.BOOST_API_KEY_DEV }}
          registry_module: boostsecurityio/native-scanner
##############################################################################################################################
#       - name: Install pre-scan dependencies
#         run: |
#           download_verify_and_unpack() {
#             (curl -s -L "$1" | tee /tmp/toxic | shasum -s -a256 -c <(echo "$3  -") && tar -C  $(dirname "$2") -xzf /tmp/toxic "$4" && if [[ ! -z "$4" ]]; then mv "$(dirname $2)/$4" "$2"; else true; fi && chmod +x "$2") || (rm -f /tmp/toxic && false)
#           }
#           download_verify_and_unpack https://get.helm.sh/helm-v3.7.1-linux-amd64.tar.gz /usr/local/bin/helm 6cd6cad4b97e10c33c978ff3ac97bb42b68f79766f1d2284cfd62ec04cd177f4 linux-amd64/helm
#       - name: Prepare pre-scan script
#         run: |
#           cat << EOF > /usr/local/bin/render-k8s.sh
#           #!/bin/bash
#           helm template canaries/helm/charts/hello-world --output-dir ./generated
#           EOF
#           chmod +x /usr/local/bin/render-k8s.sh
#       - name: Scanner
#         uses: boostsecurityio/boostsec-scanner-github@v3
#         with:
#           action: scan
#           additional_args: --pre-scan-command "/usr/local/bin/render-k8s.sh"
#           api_endpoint: https://api.dev.boostsec.io
#           step_name: scanner-dev
#           api_token: ${{ secrets.BOOST_API_KEY_DEV }}
