name: boostsecurity.io
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
jobs:
  boost_security_sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1
      - name: Native Scanner
        uses: boostsecurityio/boostsec-scanner-github@v4
        env:
          BOOST_SCANNER_REGISTRY_REPO: https://github.com/boostsecurityio/scanner-registry.git#native-scanner/maybe-wrong-id
        with:
          api_token: ${{ secrets.BOOST_API_KEY }}
          registry_module: boostsecurityio/native-scanner
          pre_scan_cmd: |
            helm template canaries/helm/charts/hello-world --output-dir ./generated
